"""Additional lessons; original questions remain in questions.py."""

CATEGORIES = [
    dict(id="thinking", title="Programming thinking", description="Break problems into steps, trace execution, and organize functions and modules."),
    dict(id="python", title="Python practice", description="Python logic, useful patterns, debugging, and common mistakes."),
    dict(id="data", title="Data & pipelines", description="PostgreSQL, pandas, and scikit-learn: clean, combine, store, and prepare data."),
    dict(id="services", title="Building services", description="Connect UI, FastAPI, application logic, and storage around a useful goal."),
    dict(id="ai", title="AI tools & systems", description="Use AI tools, guide coding agents, and understand RAG and deep learning."),
    dict(id="reliability", title="Testing & reliability", description="Test behavior, handle failures, protect data, and monitor services."),
    dict(id="statistics", title="Statistics for ML", description="Probability, distributions, sampling, uncertainty, and model evaluation."),
]

ORIGINAL_CATEGORIES = {
    "services": ["problem", "flow", "methods", "validation", "dependencies"],
    "python": ["py-normalize", "py-filter", "py-count", "py-error"],
    "data": ["relationships", "crud", "joins", "transactions", "indexes", "sql-join", "sql-table"],
    "ai": ["deep-learning", "rag", "agents"],
    "reliability": ["testing", "operations"],
}

def mc(id, category, topic, prompt, options, correct, explanation, wrong, hint, source=None):
    return dict(id=id, category=category, topic=topic, kind="choice", prompt=prompt,
                options=options, correct=correct, explanation=explanation, wrong=wrong,
                hints=[hint], source=source)

def code(id, category, topic, language, prompt, starter, hints, reference, syntax, service, pitfall, example, source=None):
    return dict(id=id, category=category, topic=topic, kind="code", language=language,
                prompt=prompt, starter=starter, hints=hints, reference=reference,
                syntax=syntax, service=service, pitfall=pitfall, example=example, source=source)

ADDITIONAL_QUESTIONS = [
    mc("think-contract", "thinking", "Inputs and outputs",
       "Before writing an order-total function, what is most useful to specify?",
       ["Inputs, output, and rules for empty or invalid orders", "Its exact line count", "A class hierarchy for every future feature", "The editor theme"], 0,
       "A contract makes a task testable: accept a list of prices, return their sum, and define the empty-list result. Concrete examples reveal missing decisions.",
       "Line counts and tools do not define correctness. Planning every future feature adds work before current rules are clear.",
       "Write one input and its expected output."),
    code("think-total", "thinking", "Separating calculation from I/O", "Python",
         "Write total_cost(prices) for a list of nonnegative numbers. Return their sum, or 0 for an empty list. Keep file reading and printing outside this function.",
         "def total_cost(prices):\n    # calculate and return\n",
         ["Work entirely with the input list.", "Python's sum() adds iterable items.", "Return sum(prices); sum([]) is 0."],
         "def total_cost(prices):\n    return sum(prices)",
         "prices is the input parameter. sum produces a number; return passes it to the caller.",
         "A route loads prices, calls the calculation, then builds a response. Tests can call the calculation without a server.",
         "Printing does not return a value. File access inside the calculation couples it to storage.",
         "total_cost([4, 6, 2]) → 12\ntotal_cost([]) → 0"),
    mc("think-trace", "thinking", "Tracing control flow",
       "A function loops over [3, 5, 8] and returns the first value greater than 4. What happens?",
       ["It returns [5, 8]", "It returns 5 and stops", "It returns 8", "It returns 3"], 1,
       "return ends the function immediately. The loop skips 3, reaches 5, and returns before examining 8.",
       "Collecting all matches requires a collection. A return inside a loop does not wait until the loop ends.",
       "Distinguish returning one answer from collecting many."),
    mc("think-boundary", "thinking", "Edge cases",
       "A function computes sum(values) / len(values). Which input exposes an unhandled boundary?",
       ["[2, 4]", "[0, 0]", "[]", "[5]"], 2,
       "An empty list has length zero. Decide whether to raise a clear error or return a documented missing value.",
       "An empty dataset has no ordinary arithmetic mean; silently returning 0 can mislead callers.",
       "What happens to the denominator?"),
    mc("think-structure", "thinking", "Choosing data structures",
       "You repeatedly check whether an integer ID was processed. Order does not matter. Which structure fits?",
       ["A set of processed IDs", "A comma-separated string", "One table per ID", "One boolean for all IDs"], 0,
       "A set stores unique, hashable values and supports efficient membership checks: item_id in seen.",
       "A boolean loses which ID was processed. String matching can confuse partial matches.",
       "You need uniqueness and membership."),
    code("think-unique", "thinking", "Preserving order", "Python",
         "Write unique_ids(ids) for integer IDs. Return each ID once, preserving its first appearance.",
         "def unique_ids(ids):\n    ...\n",
         ["Track seen IDs and append only new ones.", "Use a set for membership and a list for order.", "When an ID is absent from seen, add it and append it to result."],
         "def unique_ids(ids):\n    seen = set()\n    result = []\n    for item_id in ids:\n        if item_id not in seen:\n            seen.add(item_id)\n            result.append(item_id)\n    return result",
         "set() creates a set; in checks membership; append adds to a list's end.",
         "An import can remove repeated IDs while retaining source order.",
         "list(set(ids)) does not promise the input order. dict.fromkeys(ids) is also valid for these inputs.",
         "unique_ids([8, 3, 8, 2, 3]) → [8, 3, 2]"),
    mc("think-modules", "thinking", "Module responsibilities",
       "A calculator imports the web route module only to read a global discount. What makes it easier to reuse?",
       ["Copy the route into tests", "Pass the discount as an input", "Merge all files", "Read browser state inside the calculator"], 1,
       "Explicit inputs make dependencies visible. Routes, tests, and batch jobs can call the same calculator.",
       "Hidden globals and circular imports make behavior harder to understand and change.",
       "Which information does the function actually need?"),
    mc("think-reproduce", "thinking", "Debugging systematically",
       "A large script sometimes gives a wrong total. What should you investigate first?",
       ["Rewrite it in another language", "Disable validation", "Find the smallest input that reproduces the error", "Add random delays"], 2,
       "A small reproducible case lets you compare expected and actual values and test one hypothesis at a time.",
       "Unrelated changes make the original cause harder to identify.",
       "Reduce the problem until the failure is clear."),
    code("think-boolean", "thinking", "Expressing business rules", "Python",
         "Write can_publish(valid, approved). Both inputs are booleans. Return True only when the draft is valid AND approved.",
         "def can_publish(valid, approved):\n    ...\n",
         ["List the four possible input pairs.", "and requires both conditions; or requires at least one.", "Return valid and approved."],
         "def can_publish(valid, approved):\n    return valid and approved",
         "and combines two conditions. With boolean inputs, only True and True produces True.",
         "A workflow evaluates this rule after validation and approval checks.",
         "or allows one condition alone. This helper does not authenticate the approver.",
         "can_publish(True, True) → True\ncan_publish(True, False) → False"),
    mc("think-invariant", "thinking", "Rules that stay true",
       "A reservation system has 10 seats. Which rule should hold after every successful booking?",
       ["Every request is accepted", "Available seats are never negative", "Every function has 10 lines", "Query duration is constant"], 1,
       "An invariant is a rule every valid state shares. Stock must remain nonnegative, including with concurrent requests.",
       "Happy-path checks alone can miss simultaneous bookings that violate the rule.",
       "Think about valid stored state."),

    mc("py-print-return", "python", "Return versus print",
       "A function prints 'ready' but has no return statement. What value does its caller receive?",
       ["'ready'", "True", "None", "The console"], 2,
       "print sends text to an output stream. A function reaching its end without a return value returns None.",
       "Visible console output is not a returned value.",
       "The caller uses a return value."),
    mc("py-alias", "python", "Shared mutable objects",
       "After a = [1, 2]; b = a; b.append(3), what is a?",
       ["[1, 2]", "[1, 2, 3]", "[3]", "None"], 1,
       "Both names refer to one list. Mutating it through b is visible through a. a.copy() makes a shallow copy.",
       "Assignment does not copy objects. A shallow copy still shares nested mutable objects.",
       "Draw two arrows pointing to one list."),
    code("py-default", "python", "Mutable default arguments", "Python",
         "Write add_tag(tag, tags=None). If tags is omitted, start a fresh list. Otherwise append to the supplied list. Return the list.",
         "def add_tag(tag, tags=None):\n    ...\n",
         ["Check tags is None.", "Create tags = [] inside that branch.", "Append tag and return tags."],
         "def add_tag(tag, tags=None):\n    if tags is None:\n        tags = []\n    tags.append(tag)\n    return tags",
         "None marks an omitted list. Creating a list inside the function makes a fresh object on that call.",
         "A helper must not accidentally reuse another request's tags.",
         "A list default in the signature is created once and can accumulate changes across calls.",
         "add_tag('new') → ['new']\nadd_tag('paid') → ['paid'] on a separate call"),
    mc("py-none", "python", "Missing values versus zero",
       "A sensor value can be 0 or None. Which condition tests only for a missing reading?",
       ["if not reading:", "if reading is None:", "if reading == False:", "if reading < 1:"], 1,
       "is None checks the missing-value sentinel without treating valid zero as missing.",
       "Zero is falsy, so not reading combines two different cases.",
       "Zero still contains information."),
    mc("py-enumerate", "python", "Useful built-ins",
       "You need positions and values while iterating a list. Which built-in fits?",
       ["enumerate(items)", "len(items)", "print(items)", "items.sort()"], 0,
       "enumerate yields index/value pairs: for index, item in enumerate(items).",
       "Counting, printing, and sorting do not themselves yield these pairs.",
       "Look for a tool that counts while looping."),
    mc("py-catch", "python", "Expected errors",
       "Converting user text with int(raw) can fail. Which approach is useful?",
       ["Catch everything and return success", "Catch expected conversion errors and report invalid input", "Retry forever", "Remove all error handling"], 1,
       "Handle expected errors, such as ValueError for nonnumeric text, while leaving unexpected bugs visible for investigation.",
       "Broad silent catches can turn programming errors into misleading success.",
       "Separate invalid input from unexpected bugs."),
]

ADDITIONAL_QUESTIONS_DATA = [
    code("sql-revenue", "data", "PostgreSQL aggregation", "PostgreSQL",
         "orders has customer_id, status, and amount numeric NOT NULL. Return customer_id and total_paid for paid orders, keeping only customers with a paid total of at least 100.",
         "SELECT ...\nFROM orders\n",
         ["WHERE filters rows before grouping.", "GROUP BY customer_id and SUM(amount) calculate each total.", "HAVING SUM(amount) >= 100 filters the groups."],
         "SELECT customer_id, SUM(amount) AS total_paid\nFROM orders\nWHERE status = 'paid'\nGROUP BY customer_id\nHAVING SUM(amount) >= 100;",
         "WHERE filters rows; GROUP BY groups them; SUM aggregates; HAVING filters groups.",
         "A reporting API can identify customers above a spending threshold.",
         "WHERE SUM(amount) >= 100 is invalid here: WHERE precedes grouping. Including unpaid orders produces the wrong totals.",
         "Rows: (1, 'paid', 60), (1, 'paid', 50), (2, 'paid', 20), (2, 'new', 200)\nExpected: customer_id 1, total_paid 110"),
    mc("pipeline-retry", "data", "Idempotent ingestion",
       "An import fails after writing half its rows. How can a retry avoid duplicate records?",
       ["Give every retry new record IDs", "Use stable source keys, a uniqueness rule, and a defined upsert policy", "Disable constraints", "Assume the first attempt wrote nothing"], 1,
       "A stable key identifies the same record across attempts. A unique constraint and intentional conflict policy make repeated delivery manageable.",
       "Incrementing a counter on every retry can still duplicate effects even with an upsert.",
       "Which identifier stays the same across retries?"),
    code("sql-upsert", "data", "PostgreSQL upserts", "PostgreSQL",
         "customer_totals has customer_id integer PRIMARY KEY and total numeric. Store the latest absolute total 125.50 for customer 7. On a conflict, replace total with that value.",
         "INSERT INTO customer_totals ...\n",
         ["Insert (7, 125.50) into (customer_id, total).", "Use ON CONFLICT (customer_id) DO UPDATE.", "Set total = EXCLUDED.total."],
         "INSERT INTO customer_totals (customer_id, total)\nVALUES (7, 125.50)\nON CONFLICT (customer_id)\nDO UPDATE SET total = EXCLUDED.total;",
         "ON CONFLICT names the unique key. EXCLUDED.total is the incoming value.",
         "A pipeline can refresh a snapshot without creating duplicates when a batch is retried.",
         "Adding the incoming total would count a retried snapshot again. Real external inputs should use query parameters.",
         "Before: (7, 90.00)\nAfter first run and retry: (7, 125.50)",
         "https://www.postgresql.org/docs/current/sql-insert.html"),
    code("pandas-clean", "data", "pandas: cleaning numeric data", "Python · pandas",
         "Write clean_orders(df). Return a new DataFrame with amount converted to numbers. Discard unparseable, missing, and negative amounts. Keep zero and leave df unchanged.",
         "import pandas as pd\n\ndef clean_orders(df):\n    ...\n",
         ["Start with result = df.copy().", "pd.to_numeric(..., errors='coerce') converts invalid text to missing values.", "Keep amount.notna() & (amount >= 0) using .loc."],
         "import pandas as pd\n\ndef clean_orders(df):\n    result = df.copy()\n    result['amount'] = pd.to_numeric(result['amount'], errors='coerce')\n    return result.loc[result['amount'].notna() & (result['amount'] >= 0)].copy()",
         "A DataFrame is a table. .loc selects rows using a boolean mask. & combines element-by-element conditions.",
         "This cleans a small batch before loading a report. Production pipelines should count or quarantine rejected rows.",
         "Replacing invalid amounts with zero invents values. Python and does not combine pandas Series masks.",
         "Input amount: ['10', 'bad', None, '-3', '0']\nOutput amount: [10, 0], numeric; input unchanged",
         "https://pandas.pydata.org/docs/user_guide/missing_data.html"),
    mc("pipeline-schema", "data", "Schema drift",
       "A supplier changes amount to amount_in_cents. What should the import do?",
       ["Rename it and keep all values", "Detect the unit/schema change and require a defined conversion", "Fill amounts with zero", "Publish without that column"], 1,
       "Names, units, and types form a data contract. Validation prevents a 100-fold unit error from reaching reports or model features.",
       "Successfully reading a file does not prove the data has the expected meaning.",
       "A number's unit is part of its meaning."),
    code("pandas-daily", "data", "pandas: daily aggregation", "Python · pandas",
         "Write daily_totals(df) for timestamp and amount columns. Timestamps are valid ISO strings with timezone offsets; amounts are numeric. Return a Series of totals per UTC calendar date, sorted by date. Leave df unchanged.",
         "import pandas as pd\n\ndef daily_totals(df):\n    ...\n",
         ["Parse timestamps with pd.to_datetime(..., utc=True).", "Use .dt.floor('D') for a UTC day key.", "Group the amount Series by the day key, sum, and sort_index()."],
         "import pandas as pd\n\ndef daily_totals(df):\n    days = pd.to_datetime(df['timestamp'], utc=True).dt.floor('D')\n    return df['amount'].groupby(days).sum().sort_index()",
         "to_datetime parses times; utc=True normalizes offsets. .dt accesses datetime operations. groupby(...).sum() combines a day's values.",
         "A scheduled job can produce a daily chart using a documented timezone.",
         "Taking the first ten characters groups by the written local date, which can differ from the UTC date.",
         "timestamps: ['2026-01-02T00:30:00+09:00', '2026-01-01T16:00:00Z']\namounts: [10, 20]\nExpected: 2026-01-01 00:00 UTC → 30",
         "https://pandas.pydata.org/docs/getting_started/intro_tutorials/09_timeseries.html"),
    mc("pipeline-missing", "data", "Missingness and bias",
       "Older devices often omit a sensor field. Why can dropping all incomplete rows mislead you?",
       ["Dropping rows always improves accuracy", "Older devices may become underrepresented", "Missing always means zero", "A larger model recovers deleted rows"], 1,
       "Missingness can depend on a device or user group. Removing rows changes the population represented; measure missingness by relevant groups.",
       "No fill or drop policy is universally correct. Use field meaning and learn model preprocessing from training data.",
       "Who disappears when the rows are removed?"),
    code("pandas-merge", "data", "pandas: safe joins", "Python · pandas",
         "orders has order_id and user_id; users has user_id and email. IDs are non-null. Return a left join keeping every order. Fail if users contains duplicate user_id values.",
         "def attach_emails(orders, users):\n    ...\n",
         ["Use orders.merge(users, on='user_id', how='left', ...).", "Orders may repeat a user; users must have one row per user.", "validate='many_to_one' checks right-side uniqueness."],
         "def attach_emails(orders, users):\n    return orders.merge(users, on='user_id', how='left', validate='many_to_one')",
         "how='left' preserves left-side rows. validate checks the intended key relationship.",
         "A reporting pipeline enriches orders and detects a broken user table before totals are inflated.",
         "Many-to-many joins can multiply rows. An inner join drops orders whose users are missing.",
         "Orders: user IDs [1, 2]; users: only ID 1\nExpected: two rows, ID 2 has missing email. Duplicate ID 1 in users must raise an error.",
         "https://pandas.pydata.org/docs/reference/api/pandas.merge.html"),
    mc("pipeline-memory", "data", "Large-file processing",
       "A CSV exceeds available RAM. What works when partial results can be combined correctly?",
       ["Keep trying a full read", "Read needed columns in chunks and combine partial aggregates", "Convert numbers to long strings", "Publish an empty report on MemoryError"], 1,
       "Chunking bounds memory use. A global mean needs total sum and count, not an unweighted average of differently sized chunk means.",
       "Global deduplication still needs shared state or storage. Chunking alone does not fix every algorithm.",
       "Which work is local to a chunk, and which spans the file?"),
    code("sklearn-preprocess", "data", "scikit-learn: preventing leakage", "Python · scikit-learn",
         "Build a Pipeline named prep to fill missing numeric values with the training median, then standardize features. Create train_ready and test_ready from X_train and X_test. No training feature is entirely missing.",
         "from sklearn.pipeline import Pipeline\nfrom sklearn.impute import SimpleImputer\nfrom sklearn.preprocessing import StandardScaler\n\n# build prep and transform both datasets\n",
         ["Use SimpleImputer(strategy='median') and StandardScaler() as named steps.", "Fit preprocessing only on X_train.", "Call fit_transform on training data and transform on test data."],
         "from sklearn.pipeline import Pipeline\nfrom sklearn.impute import SimpleImputer\nfrom sklearn.preprocessing import StandardScaler\n\nprep = Pipeline([\n    ('impute', SimpleImputer(strategy='median')),\n    ('scale', StandardScaler()),\n])\ntrain_ready = prep.fit_transform(X_train)\ntest_ready = prep.transform(X_test)",
         "A Pipeline applies steps in sequence. fit learns parameters; transform applies the learned parameters.",
         "Reuse fitted preprocessing at prediction time. For cross-validation, include preprocessing and estimator in the pipeline being evaluated.",
         "Fitting on test data leaks information. Fitting a separate test scaler changes what transformed values mean.",
         "X_train: [[1], [3], [NaN]]; X_test: [[NaN]]\nTraining median: 2. Transformed missing test value: 0.",
         "https://scikit-learn.org/stable/common_pitfalls.html"),
]

ADDITIONAL_QUESTIONS += ADDITIONAL_QUESTIONS_DATA
ADDITIONAL_QUESTIONS += [
    mc("service-owner", "services", "Server-side authorization",
       "The UI hides a note-edit button unless you own the note. What must the API still do?",
       ["Trust the hidden button", "Check the authenticated user's permission for that note", "Trust any submitted user_id", "Use hard-to-remember IDs"], 1,
       "The server must authorize each operation against the resource. A script can send requests without the UI.",
       "Authentication identifies a caller; authorization checks what they may do. Hidden controls enforce neither on the server.",
       "A caller can bypass the page."),
    code("fastapi-quantity", "services", "Validating request bodies", "Python · FastAPI",
         "Create a FastAPI app with POST /quantity. Accept a JSON body containing an integer quantity greater than zero and return {'quantity': value}. Use a Pydantic model and Field(gt=0).",
         "from fastapi import FastAPI\nfrom pydantic import BaseModel, Field\n\napp = FastAPI()\n",
         ["Define a BaseModel subclass.", "Declare quantity: int = Field(gt=0).", "Register a POST handler with a model-typed parameter and return its quantity."],
         "from fastapi import FastAPI\nfrom pydantic import BaseModel, Field\n\napp = FastAPI()\n\nclass QuantityInput(BaseModel):\n    quantity: int = Field(gt=0)\n\n@app.post('/quantity')\ndef accept_quantity(body: QuantityInput):\n    return {'quantity': body.quantity}",
         "The model describes the body. Field constrains the value. The decorator connects an HTTP method and path to a function.",
         "Validation happens before application logic uses the quantity. This small endpoint does not store an order.",
         "An int annotation alone allows negative values. UI-only checks can be bypassed.",
         "Body {'quantity': 3} → {'quantity': 3}\nBody {'quantity': 0} → validation error, HTTP 422"),
    mc("service-scope", "services", "Avoiding unnecessary complexity",
       "You are validating a small internal notes tool. Which first design is easiest to evaluate and evolve?",
       ["A dozen services before user feedback", "One application with clear modules, a simple schema, and acceptance checks", "An AI agent for every database read", "No error paths until launch"], 1,
       "A small complete version tests the workflow's value. Clear module boundaries and data contracts leave room to grow.",
       "Extra infrastructure has costs. Add it for measured needs rather than predicted scale alone.",
       "Choose the smallest complete service that tests the intended value."),

    mc("ai-context", "ai", "Useful prompting",
       "Which request gives an AI assistant useful direction for improving a signup page?",
       ["Make it amazing", "Use more AI", "Explain all websites", "Reduce first-time-user confusion; use this screenshot and keep required fields"], 3,
       "The request gives a goal, audience, evidence, and constraint so changes can be evaluated.",
       "Vague adjectives leave success unstated. More text helps only when it changes what a good result means.",
       "Name the outcome and useful context.",
       "https://learn.chatgpt.com/docs/prompting"),
    mc("ai-verify", "ai", "Checking AI output",
       "An AI answer confidently cites a paper for a number. What should you do before relying on it?",
       ["Trust the citation", "Open the source and check the exact claim and context", "Ask for a more confident tone", "Count its paragraphs"], 1,
       "Verify that the source exists and supports the claim. Check dates and context as well as the number.",
       "Confidence and formatting are not evidence. Asking the same assistant to agree again is not an independent check.",
       "Does the source actually say what the answer claims?",
       "https://learn.chatgpt.com/docs/use-chatgpt"),
    mc("ai-learning", "ai", "Learning with AI",
       "You want help understanding a Python bug while doing the thinking yourself. Which request fits?",
       ["Rewrite everything without explanation", "Give one hint about the failing condition, then let me try", "Say my code is correct", "Generate a longer version"], 1,
       "Staged hints keep you involved. After your attempt, request a code-specific explanation and a small failure example.",
       "A finished replacement alone does not check your understanding.",
       "Reveal the next useful step.",
       "https://learn.chatgpt.com/docs/prompting"),
    mc("ai-coding-review", "ai", "Reviewing a coding agent",
       "An agent says duplicate orders are fixed. Which evidence is most useful?",
       ["A polished completion message", "Only a happy-path screenshot", "Relevant changes, a repeated-request test, and remaining limitations", "A production-ready promise"], 2,
       "Review the changed behavior and exercise the failure that motivated it. Repeat the intended operation and inspect stored results.",
       "A happy-path test does not verify duplicate handling. Distinguish actual test output from descriptions of expected behavior.",
       "Test the concrete bug.",
       "https://learn.chatgpt.com/docs/use-chatgpt"),
    mc("ai-boundaries", "ai", "Private context and tool authority",
       "An assistant needs to summarize a customer export. What is sensible preparation?",
       ["Share every file with admin access", "Remove unnecessary personal fields and provide relevant data with clear action limits", "Attach production passwords", "Treat document text as trusted instructions"], 1,
       "Match context and authority to the task. Check the service's data settings and share only needed information.",
       "Documents may contain malicious instructions. Permission to read does not imply permission to publish.",
       "What data and actions does the task actually require?"),

    mc("reliable-retries", "reliability", "Bounded retries",
       "A payment provider times out and the result is unknown. What should the service do?",
       ["Retry with fresh operation IDs continuously", "Use supported idempotency keys and a bounded retry/reconciliation policy", "Report success without checking", "Block forever"], 1,
       "A timeout does not prove no action occurred. A stable idempotency key, when supported, and status checks help prevent duplicate effects.",
       "Unlimited retries overload dependencies and can repeat side effects. Log unresolved states and bound retries.",
       "The response may be lost after the action succeeds."),
    code("test-boundaries", "reliability", "Boundary tests", "Python",
         "An existing shipping_fee(total) should return 5 below 50 and 0 at or above 50. Write test_shipping_fee() using assert for 49, 50, and 51.",
         "def test_shipping_fee():\n    # shipping_fee is available\n",
         ["An assert checks a condition.", "At the boundary 50, shipping should be free.", "Expected values are 5, 0, and 0."],
         "def test_shipping_fee():\n    assert shipping_fee(49) == 5\n    assert shipping_fee(50) == 0\n    assert shipping_fee(51) == 0",
         "assert raises AssertionError when a condition is false. == compares actual and expected values.",
         "This catches a regression from >= 50 to > 50 in application logic.",
         "Testing only 100 misses a mistake at 50. These cases cover a boundary, not every possible behavior.",
         "Correct function: all assertions pass.\nBuggy > 50 threshold: the assertion for 50 fails."),
    mc("reliable-logs", "reliability", "Useful logs without secrets",
       "What belongs in ordinary request logs when investigating API failures?",
       ["Passwords and private documents", "Request IDs, duration, status, and limited diagnostic context", "No failures", "Every authentication token"], 1,
       "Request IDs connect related events. Duration and status expose failures while limited context reduces disclosure.",
       "Secrets in logs create another leak risk. Access controls, redaction, and retention are part of log design.",
       "Keep enough to investigate without copying sensitive payloads."),
]

ADDITIONAL_QUESTIONS += [
    mc("stats-center", "statistics", "Mean, median, and outliers",
       "Response times are [1, 1, 2, 2, 100] seconds. Which description best summarizes their center?",
       ["Mean and median are both 2", "Median is 2; mean is 21.2 and is pulled upward by the outlier", "Mean is always the most typical observation", "The outlier should always be deleted"], 1,
       "The median is the middle sorted value. The mean uses every value, so the slow request affects it strongly. Investigate outliers instead of deleting them automatically.",
       "A single average can hide important behavior. In monitoring, also inspect tail percentiles and failure cases.",
       "Sort the observations, then separately calculate sum divided by count."),
    mc("stats-spread", "statistics", "Variance and standard deviation",
       "Two models have the same mean prediction error but different error standard deviations. What does the larger standard deviation describe?",
       ["Greater spread around the mean error", "A larger sample size", "Proof of causation", "The probability every prediction is correct"], 0,
       "Variance averages squared deviations under a stated convention. Standard deviation is its square root, in the original units. Spread differs from uncertainty in an estimated mean.",
       "Standard error concerns an estimator's sampling variability. For an independent sample mean it is commonly estimated as sample standard deviation divided by sqrt(n).",
       "Separate variation among observations from uncertainty in an average."),
    code("numpy-spread", "statistics", "NumPy: sample standard deviation", "Python · NumPy",
         "Write sample_sd(values) using NumPy. Values are a finite, one-dimensional numeric sequence. Return the sample standard deviation using denominator n - 1. Raise ValueError for fewer than two values.",
         "import numpy as np\n\ndef sample_sd(values):\n    ...\n",
         ["Check len(values) before calculating.", "np.std uses denominator n - ddof; ddof=1 gives n - 1.", "Return float(np.std(values, ddof=1))."],
         "import numpy as np\n\ndef sample_sd(values):\n    if len(values) < 2:\n        raise ValueError('Need at least two values')\n    return float(np.std(values, ddof=1))",
         "ddof changes the divisor. raise signals invalid input. float returns a regular Python number.",
         "This summarizes variability in a sampled feature or metric. The intended population and sampling method still matter.",
         "NumPy defaults to ddof=0. The n-1 correction makes sample variance unbiased under common independent sampling assumptions; its square root is not generally an unbiased estimator of population standard deviation.",
         "sample_sd([1, 2, 3]) → 1.0\nsample_sd([3]) → ValueError",
         "https://numpy.org/doc/stable/reference/generated/numpy.std.html"),
    mc("stats-base-rate", "statistics", "Conditional probability and base rates",
       "Among 1,000 items, 10 are truly defective. A detector flags 9 of those and also flags 99 good items. About what fraction of flagged items are defective?",
       ["90%", "99%", "8.3%", "1%"], 2,
       "There are 108 flags, and 9 are true defects: 9/108 ≈ 8.3%. This is precision, the conditional probability of a defect given a flag in this sample.",
       "The detector found 9/10 defects (90% recall), but that answers a different question. Low prevalence can make false positives dominate.",
       "Use all flagged items as the denominator."),
    code("scipy-binomial", "statistics", "SciPy: binomial probability", "Python · SciPy",
         "Each of 5 independent requests fails with probability 0.1. Use scipy.stats.binom to assign the probability of exactly 2 failures to probability.",
         "from scipy.stats import binom\n\nprobability = ...\n",
         ["A binomial count assumes fixed n, constant p, and independent trials.", "pmf(k, n, p) gives the probability of exactly k successes.", "Here a 'success' for the count means a failure: k=2, n=5, p=0.1."],
         "from scipy.stats import binom\n\nprobability = binom.pmf(2, n=5, p=0.1)",
         "pmf is the probability mass function for a discrete count. Named arguments identify the number of trials and per-trial probability.",
         "This is a simple probability model for independent outcomes. Its expected failure count is n*p = 0.5.",
         "cdf(2) includes 0, 1, and 2 failures. Correlated outages violate independence, so the binomial estimate may be unrealistic.",
         "Expected probability: 0.0729 (7.29%)",
         "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.binom.html"),
    mc("stats-sampling", "statistics", "Sampling and selection bias",
       "You evaluate a support model using only users who voluntarily rated successful chats. What is the main concern?",
       ["The sample may exclude dissatisfied users and failures", "More decimal places will fix the sample", "A large sample can never be biased", "All surveys are useless"], 0,
       "Selection determines whose outcomes are represented. Sample both successes and failures across relevant users, and inspect important subgroups.",
       "More observations can reduce random variation while leaving systematic selection bias intact.",
       "Who is missing from the evaluation?"),
    mc("stats-interval", "statistics", "Confidence intervals",
       "What does a frequentist 95% confidence-interval procedure mean under its assumptions?",
       ["95% of observations must lie inside each interval", "Across repeated samples, about 95% of the computed intervals cover the fixed parameter", "The model is correct 95% of the time", "The observed interval proves the parameter equals its midpoint"], 1,
       "The 95% describes long-run coverage of the procedure. An interval communicates sampling uncertainty; its validity depends on the sampling and model assumptions.",
       "It is not a prediction interval for individual observations, nor proof that selection bias is absent.",
       "Imagine collecting new samples and calculating a new interval each time.",
       "https://www.itl.nist.gov/div898/handbook/eda/section3/eda352.htm"),
    mc("stats-pvalue", "statistics", "Statistical versus practical importance",
       "A huge A/B test finds p=0.001 for a tiny improvement. What should you assess next?",
       ["Assume a 99.9% chance the new version is better", "Effect size, uncertainty, test assumptions, and whether the benefit matters in practice", "Ignore operating costs", "Repeat many tests until one looks impressive"], 1,
       "A p-value describes how unusual results at least this extreme would be under a specified null model. It does not measure effect size or the probability that the null is true.",
       "A tiny effect may be detectable with a large sample yet not justify cost. Multiple testing and repeated peeking need appropriate handling.",
       "Statistical evidence and practical value answer different questions."),
    mc("stats-correlation", "statistics", "Correlation and causation",
       "Users who use a new feature also retain better. Why is that not enough to claim the feature caused retention?",
       ["Correlation always means no relationship", "Already-engaged users may be more likely to use the feature", "Retention cannot be measured", "A larger neural network proves causation"], 1,
       "A confounder such as prior engagement can influence both feature use and retention. A well-designed randomized experiment can help estimate a causal effect.",
       "Correlation can be useful for prediction, but it does not alone establish what happens if you intervene.",
       "Could a third factor explain both?"),
    mc("stats-overfit", "statistics", "Generalization and overfitting",
       "Training loss keeps falling while validation loss rises. What is a likely interpretation?",
       ["Guaranteed improvement on new data", "The model may be fitting training-specific noise", "The validation set must be wrong", "Training and validation losses must be identical"], 1,
       "This pattern suggests overfitting. Consider capacity, regularization, early stopping, and data quality, while keeping a separate final test set.",
       "Lower training loss does not guarantee better generalization. Do not repeatedly tune choices on the final test set.",
       "Which metric reflects data not used to fit the parameters?"),
    code("numpy-logloss", "statistics", "Probability and deep-learning loss", "Python · NumPy",
         "Write binary_log_loss(y, p) using NumPy. y is a nonempty 1D sequence of 0/1 labels; p has the same length and contains predicted probabilities strictly between 0 and 1. Return mean binary cross-entropy using natural logs.",
         "import numpy as np\n\ndef binary_log_loss(y, p):\n    ...\n",
         ["Convert both sequences to arrays with dtype=float.", "Per item, use -(y*log(p) + (1-y)*log(1-p)).", "Take np.mean of those losses and return a float."],
         "import numpy as np\n\ndef binary_log_loss(y, p):\n    y = np.asarray(y, dtype=float)\n    p = np.asarray(p, dtype=float)\n    losses = -(y * np.log(p) + (1 - y) * np.log(1 - p))\n    return float(np.mean(losses))",
         "Array operations work elementwise. np.log is natural logarithm. np.mean averages the per-example losses.",
         "Binary classifiers, including neural networks, often optimize this negative log-likelihood loss. It penalizes confident wrong predictions strongly.",
         "Accuracy ignores confidence. log(0) is undefined; the prompt excludes endpoints. Production frameworks use numerically stable implementations, often directly from logits.",
         "binary_log_loss([1, 0], [0.8, 0.2]) ≈ 0.22314",
         "https://scikit-learn.org/stable/modules/generated/sklearn.metrics.log_loss.html"),
    mc("stats-imbalance", "statistics", "Class imbalance and evaluation",
       "Only 1% of examples are positive. A model predicts negative every time and gets 99% accuracy. What else should you examine?",
       ["Nothing; 99% proves usefulness", "Positive-class precision/recall and error costs, against a baseline", "Only training accuracy", "Only parameter count"], 1,
       "This model finds none of the positives: recall is zero. Choose metrics and decision thresholds based on the costs of misses and false alarms.",
       "A high aggregate score can hide failure on a rare class. Evaluate on representative held-out data and inspect relevant subgroups.",
       "What did the model do for the rare class?"),
]
